"use client";
import type { Metadata } from "next";
import "../assets/css/globals.css";
import { ApolloProvider } from "@apollo/client/react";
import client from "@/shared/utils/apollo-client";
import Header from "../components/Header";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloProvider client={client}>
          <Header />
          <div className="h-[calc(100vh-5rem)] pt-20 px-5">{children}</div>
        </ApolloProvider>
      </body>
    </html>
  );
}
